### ISSUE TITLE
Pip 安装后import提示报错 “ModuleNotFoundError: No module named 'MercurySQL.drivers'”

### ISSUE THREAD

**Issue by lanbinshijie** [BernieHuang2008/MercurySQL#2]
版本：Stable 0.0.5

报错信息：
```bash
Traceback (most recent call last):
  File "D:\Desktop\MercurySQL Learning\main.py", line 1, in <module>
    import MercurySQL as ms
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\MercurySQL\__init__.py", line 17, in <module>
    from .base import DataBase, Table
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\MercurySQL\base.py", line 84, in <module>
    from .drivers.base import BaseDriver
ModuleNotFoundError: No module named 'MercurySQL.drivers'
```

报错代码：
```python
import MercurySQL as ms

db = ms.DataBase("base.db")
```

安装方式：
> pip install MercurySQL

错误截图：
<img width="1280" alt="image" src="https://github.com/BernieHuang2008/MercurySQL/assets/62149873/78a75ece-a920-41c5-9fa6-64c22cc0d196">

**Comment by lanbinshijie** [comment]
@BernieHuang2008 我觉得可能是drivers没有一起打包？你要不创建个环境试试，还是我的代码有问题？

<img width="384" alt="image" src="https://github.com/BernieHuang2008/MercurySQL/assets/62149873/e3d3891b-1892-4d67-8e3c-7cad66d71733">

<img width="557" alt="image" src="https://github.com/BernieHuang2008/MercurySQL/assets/62149873/1417f423-2d5b-4302-aea4-b49c09347e9b">

**Init和Base里面都有这个import，其他我没看**

**Comment by BernieHuang2008** [comment]
0.0.5是有问题的版本，周末改。

但是这个代码应该很好解决，试着把.drivers前面的点去掉？

**Comment by BernieHuang2008** [comment]
看看base.py旁边有没有drivers文件夹

**Comment by BernieHuang2008** [comment]
BaseDriver好像很废，只是用于限制变量类型，删掉不会对功能产生影响

**Comment by BernieHuang2008** [comment]
我现在是手机，周末才有电脑

**Comment by lanbinshijie** [comment]
> 我现在是手机，周末才有电脑

没问题

**Comment by BernieHuang2008** [comment]
solved in [v0.0.8](https://github.com/BernieHuang2008/MercurySQL/releases/tag/v0.0.8)
